name: Build and Publish Swift-DocC Docs

on:
  push:
    branches:
      - dev-1  # change if your default branch is different

jobs:
  build-docs:
    runs-on: macos-latest
    steps:
      # - uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: latest-stable

      - uses: actions/checkout@v3

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # needed for pushing back to gh-pages

      # - name: Check Swift version
        # run: swift --version
        
      # - name: Build doc archive
      #   run: swift package --allow-writing-to-directory ./docs generate-documentation --target ObjeKit --disable-indexing --transform-for-static-hosting --hosting-base-path https://njazz.github.io/ObjeKit/ --output-path ./docs

      - name: Set up Ruby and install Jazzy
        run: |
          sudo gem install jazzy

      - name: Generate Jazzy docs
        run: |
          jazzy \
            --module ObjeKit \
            --swift-build-tool spm \
            --output ./docs
            
      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
