name: Build and Publish Swift-DocC Docs

on:
  push:
    branches:
      - dev-1  # change if your default branch is different

jobs:
  build-docs:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [14.0, 14.2]  # Choose the minimum Xcode 14 version you want

    steps:
      - uses: actions/checkout@v3

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # needed for pushing back to gh-pages
  
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Check Swift version
        run: swift --version

      - name: Build Swift-DocC documentation
        run: swift package generate-documentation --target ObjeKit --output-path docs --format html

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
